# Generated by Django 6.0.2 on 2026-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_alter_capsule_last_update_alter_capsule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='missions_count',
            field=models.IntegerField(default=0),
        ),
    ]
