# Generated by Django 6.0.2 on 2026-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_capsule_missions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='spacex_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
