# Generated by Django 6.0.2 on 2026-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_alter_capsule_spacex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='missions_count',
            field=models.IntegerField(),
        ),
    ]
