# Generated by Django 6.0.1 on 2026-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacex_id', models.CharField(max_length=255, unique=True)),
                ('serial', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('last_update', models.TextField(blank=True, null=True)),
                ('missions_data', models.JSONField(default=list)),
                ('is_locally_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
