# Generated by Django 6.0.1 on 2026-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='last_update',
            field=models.CharField(blank=True, choices=[('updated', 'Mis à jour'), ('pending', 'En attente'), ('verified', 'Vérifié')], default='pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('destroyed', 'Destroyed'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
