# Generated by Django 6.0.2 on 2026-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_alter_capsule_missions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='missions_count',
            field=models.IntegerField(default=0),
        ),
    ]
