# Generated by Django 6.0.2 on 2026-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_alter_capsule_missions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='last_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
